site_logo_url: 
site_name: Alakanuk Braves
email: 
phone: (907) 238-3312
address: Alakanuk School, Alakanuk, AK 99554
ga_id: 
head_code: ''
footer_code: ''
social:
  - name: Facebook
    link: https://facebook.com/alakanuk.brave.5
    icon: facebook

